version = 1

test_patterns = [".tmp"]

exclude_patterns = ["min.js"]

[[analyzers]]
name = "python"
enabled = true

  [analyzers.meta]
  runtime_version = "3.x.x"

[[analyzers]]
name = "javascript"
enabled = true

[[transformers]]
name = "black"
enabled = true
